random_seed: 1337

data:
  # Directory of PE samples
  input_dir: "${SAMPLES_DIR}"
  features_out: "${OUTPUTS_DIR}/features.parquet"
  label_source: "folder"   # infer label by parent directory name

model:
  type: "sklearn_baseline" # TODO: placeholder
  params:
    n_estimators: 100
    max_depth: null
    random_state: 1337

train:
  test_size: 0.2
  stratify: true
  out_model_path: "${ARTIFACTS_DIR}/baseline.joblib"
